/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int BAbt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int BAbt_alloc_mem(void);
int BAbt_init_mem(int mem);
void BAbt_free_mem(int mem);
int BAbt_checkout(void);
void BAbt_release(int mem);
void BAbt_incref(void);
void BAbt_decref(void);
casadi_int BAbt_n_in(void);
casadi_int BAbt_n_out(void);
casadi_real BAbt_default_in(casadi_int i);
const char* BAbt_name_in(casadi_int i);
const char* BAbt_name_out(casadi_int i);
const casadi_int* BAbt_sparsity_in(casadi_int i);
const casadi_int* BAbt_sparsity_out(casadi_int i);
int BAbt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int BAbt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define BAbt_SZ_ARG 61
#define BAbt_SZ_RES 25
#define BAbt_SZ_IW 0
#define BAbt_SZ_W 2731
int bk(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int bk_alloc_mem(void);
int bk_init_mem(int mem);
void bk_free_mem(int mem);
int bk_checkout(void);
void bk_release(int mem);
void bk_incref(void);
void bk_decref(void);
casadi_int bk_n_in(void);
casadi_int bk_n_out(void);
casadi_real bk_default_in(casadi_int i);
const char* bk_name_in(casadi_int i);
const char* bk_name_out(casadi_int i);
const casadi_int* bk_sparsity_in(casadi_int i);
const casadi_int* bk_sparsity_out(casadi_int i);
int bk_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int bk_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define bk_SZ_ARG 25
#define bk_SZ_RES 20
#define bk_SZ_IW 0
#define bk_SZ_W 306
int RSQrqtI(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int RSQrqtI_alloc_mem(void);
int RSQrqtI_init_mem(int mem);
void RSQrqtI_free_mem(int mem);
int RSQrqtI_checkout(void);
void RSQrqtI_release(int mem);
void RSQrqtI_incref(void);
void RSQrqtI_decref(void);
casadi_int RSQrqtI_n_in(void);
casadi_int RSQrqtI_n_out(void);
casadi_real RSQrqtI_default_in(casadi_int i);
const char* RSQrqtI_name_in(casadi_int i);
const char* RSQrqtI_name_out(casadi_int i);
const casadi_int* RSQrqtI_sparsity_in(casadi_int i);
const casadi_int* RSQrqtI_sparsity_out(casadi_int i);
int RSQrqtI_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int RSQrqtI_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define RSQrqtI_SZ_ARG 140
#define RSQrqtI_SZ_RES 25
#define RSQrqtI_SZ_IW 14
#define RSQrqtI_SZ_W 6454
int RSQrqtIGN(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int RSQrqtIGN_alloc_mem(void);
int RSQrqtIGN_init_mem(int mem);
void RSQrqtIGN_free_mem(int mem);
int RSQrqtIGN_checkout(void);
void RSQrqtIGN_release(int mem);
void RSQrqtIGN_incref(void);
void RSQrqtIGN_decref(void);
casadi_int RSQrqtIGN_n_in(void);
casadi_int RSQrqtIGN_n_out(void);
casadi_real RSQrqtIGN_default_in(casadi_int i);
const char* RSQrqtIGN_name_in(casadi_int i);
const char* RSQrqtIGN_name_out(casadi_int i);
const casadi_int* RSQrqtIGN_sparsity_in(casadi_int i);
const casadi_int* RSQrqtIGN_sparsity_out(casadi_int i);
int RSQrqtIGN_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int RSQrqtIGN_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define RSQrqtIGN_SZ_ARG 140
#define RSQrqtIGN_SZ_RES 25
#define RSQrqtIGN_SZ_IW 14
#define RSQrqtIGN_SZ_W 6526
int rqI(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int rqI_alloc_mem(void);
int rqI_init_mem(int mem);
void rqI_free_mem(int mem);
int rqI_checkout(void);
void rqI_release(int mem);
void rqI_incref(void);
void rqI_decref(void);
casadi_int rqI_n_in(void);
casadi_int rqI_n_out(void);
casadi_real rqI_default_in(casadi_int i);
const char* rqI_name_in(casadi_int i);
const char* rqI_name_out(casadi_int i);
const casadi_int* rqI_sparsity_in(casadi_int i);
const casadi_int* rqI_sparsity_out(casadi_int i);
int rqI_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int rqI_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define rqI_SZ_ARG 13
#define rqI_SZ_RES 2
#define rqI_SZ_IW 0
#define rqI_SZ_W 149
int RSQrqt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int RSQrqt_alloc_mem(void);
int RSQrqt_init_mem(int mem);
void RSQrqt_free_mem(int mem);
int RSQrqt_checkout(void);
void RSQrqt_release(int mem);
void RSQrqt_incref(void);
void RSQrqt_decref(void);
casadi_int RSQrqt_n_in(void);
casadi_int RSQrqt_n_out(void);
casadi_real RSQrqt_default_in(casadi_int i);
const char* RSQrqt_name_in(casadi_int i);
const char* RSQrqt_name_out(casadi_int i);
const casadi_int* RSQrqt_sparsity_in(casadi_int i);
const casadi_int* RSQrqt_sparsity_out(casadi_int i);
int RSQrqt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int RSQrqt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define RSQrqt_SZ_ARG 140
#define RSQrqt_SZ_RES 25
#define RSQrqt_SZ_IW 14
#define RSQrqt_SZ_W 6454
int RSQrqtGN(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int RSQrqtGN_alloc_mem(void);
int RSQrqtGN_init_mem(int mem);
void RSQrqtGN_free_mem(int mem);
int RSQrqtGN_checkout(void);
void RSQrqtGN_release(int mem);
void RSQrqtGN_incref(void);
void RSQrqtGN_decref(void);
casadi_int RSQrqtGN_n_in(void);
casadi_int RSQrqtGN_n_out(void);
casadi_real RSQrqtGN_default_in(casadi_int i);
const char* RSQrqtGN_name_in(casadi_int i);
const char* RSQrqtGN_name_out(casadi_int i);
const casadi_int* RSQrqtGN_sparsity_in(casadi_int i);
const casadi_int* RSQrqtGN_sparsity_out(casadi_int i);
int RSQrqtGN_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int RSQrqtGN_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define RSQrqtGN_SZ_ARG 140
#define RSQrqtGN_SZ_RES 25
#define RSQrqtGN_SZ_IW 14
#define RSQrqtGN_SZ_W 6526
int rqk(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int rqk_alloc_mem(void);
int rqk_init_mem(int mem);
void rqk_free_mem(int mem);
int rqk_checkout(void);
void rqk_release(int mem);
void rqk_incref(void);
void rqk_decref(void);
casadi_int rqk_n_in(void);
casadi_int rqk_n_out(void);
casadi_real rqk_default_in(casadi_int i);
const char* rqk_name_in(casadi_int i);
const char* rqk_name_out(casadi_int i);
const casadi_int* rqk_sparsity_in(casadi_int i);
const casadi_int* rqk_sparsity_out(casadi_int i);
int rqk_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int rqk_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define rqk_SZ_ARG 13
#define rqk_SZ_RES 2
#define rqk_SZ_IW 0
#define rqk_SZ_W 149
int LI(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int LI_alloc_mem(void);
int LI_init_mem(int mem);
void LI_free_mem(int mem);
int LI_checkout(void);
void LI_release(int mem);
void LI_incref(void);
void LI_decref(void);
casadi_int LI_n_in(void);
casadi_int LI_n_out(void);
casadi_real LI_default_in(casadi_int i);
const char* LI_name_in(casadi_int i);
const char* LI_name_out(casadi_int i);
const casadi_int* LI_sparsity_in(casadi_int i);
const casadi_int* LI_sparsity_out(casadi_int i);
int LI_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int LI_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define LI_SZ_ARG 7
#define LI_SZ_RES 2
#define LI_SZ_IW 0
#define LI_SZ_W 20
int Lk(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int Lk_alloc_mem(void);
int Lk_init_mem(int mem);
void Lk_free_mem(int mem);
int Lk_checkout(void);
void Lk_release(int mem);
void Lk_incref(void);
void Lk_decref(void);
casadi_int Lk_n_in(void);
casadi_int Lk_n_out(void);
casadi_real Lk_default_in(casadi_int i);
const char* Lk_name_in(casadi_int i);
const char* Lk_name_out(casadi_int i);
const casadi_int* Lk_sparsity_in(casadi_int i);
const casadi_int* Lk_sparsity_out(casadi_int i);
int Lk_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int Lk_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define Lk_SZ_ARG 7
#define Lk_SZ_RES 2
#define Lk_SZ_IW 0
#define Lk_SZ_W 20
int RSQrqtF(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int RSQrqtF_alloc_mem(void);
int RSQrqtF_init_mem(int mem);
void RSQrqtF_free_mem(int mem);
int RSQrqtF_checkout(void);
void RSQrqtF_release(int mem);
void RSQrqtF_incref(void);
void RSQrqtF_decref(void);
casadi_int RSQrqtF_n_in(void);
casadi_int RSQrqtF_n_out(void);
casadi_real RSQrqtF_default_in(casadi_int i);
const char* RSQrqtF_name_in(casadi_int i);
const char* RSQrqtF_name_out(casadi_int i);
const casadi_int* RSQrqtF_sparsity_in(casadi_int i);
const casadi_int* RSQrqtF_sparsity_out(casadi_int i);
int RSQrqtF_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int RSQrqtF_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define RSQrqtF_SZ_ARG 14
#define RSQrqtF_SZ_RES 7
#define RSQrqtF_SZ_IW 12
#define RSQrqtF_SZ_W 831
int RSQrqtFGN(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int RSQrqtFGN_alloc_mem(void);
int RSQrqtFGN_init_mem(int mem);
void RSQrqtFGN_free_mem(int mem);
int RSQrqtFGN_checkout(void);
void RSQrqtFGN_release(int mem);
void RSQrqtFGN_incref(void);
void RSQrqtFGN_decref(void);
casadi_int RSQrqtFGN_n_in(void);
casadi_int RSQrqtFGN_n_out(void);
casadi_real RSQrqtFGN_default_in(casadi_int i);
const char* RSQrqtFGN_name_in(casadi_int i);
const char* RSQrqtFGN_name_out(casadi_int i);
const casadi_int* RSQrqtFGN_sparsity_in(casadi_int i);
const casadi_int* RSQrqtFGN_sparsity_out(casadi_int i);
int RSQrqtFGN_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int RSQrqtFGN_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define RSQrqtFGN_SZ_ARG 14
#define RSQrqtFGN_SZ_RES 7
#define RSQrqtFGN_SZ_IW 12
#define RSQrqtFGN_SZ_W 854
int rqF(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int rqF_alloc_mem(void);
int rqF_init_mem(int mem);
void rqF_free_mem(int mem);
int rqF_checkout(void);
void rqF_release(int mem);
void rqF_incref(void);
void rqF_decref(void);
casadi_int rqF_n_in(void);
casadi_int rqF_n_out(void);
casadi_real rqF_default_in(casadi_int i);
const char* rqF_name_in(casadi_int i);
const char* rqF_name_out(casadi_int i);
const casadi_int* rqF_sparsity_in(casadi_int i);
const casadi_int* rqF_sparsity_out(casadi_int i);
int rqF_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int rqF_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define rqF_SZ_ARG 7
#define rqF_SZ_RES 2
#define rqF_SZ_IW 0
#define rqF_SZ_W 125
int LF(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int LF_alloc_mem(void);
int LF_init_mem(int mem);
void LF_free_mem(int mem);
int LF_checkout(void);
void LF_release(int mem);
void LF_incref(void);
void LF_decref(void);
casadi_int LF_n_in(void);
casadi_int LF_n_out(void);
casadi_real LF_default_in(casadi_int i);
const char* LF_name_in(casadi_int i);
const char* LF_name_out(casadi_int i);
const casadi_int* LF_sparsity_in(casadi_int i);
const casadi_int* LF_sparsity_out(casadi_int i);
int LF_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int LF_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define LF_SZ_ARG 7
#define LF_SZ_RES 2
#define LF_SZ_IW 0
#define LF_SZ_W 20
int GgtI(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int GgtI_alloc_mem(void);
int GgtI_init_mem(int mem);
void GgtI_free_mem(int mem);
int GgtI_checkout(void);
void GgtI_release(int mem);
void GgtI_incref(void);
void GgtI_decref(void);
casadi_int GgtI_n_in(void);
casadi_int GgtI_n_out(void);
casadi_real GgtI_default_in(casadi_int i);
const char* GgtI_name_in(casadi_int i);
const char* GgtI_name_out(casadi_int i);
const casadi_int* GgtI_sparsity_in(casadi_int i);
const casadi_int* GgtI_sparsity_out(casadi_int i);
int GgtI_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int GgtI_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define GgtI_SZ_ARG 15
#define GgtI_SZ_RES 9
#define GgtI_SZ_IW 0
#define GgtI_SZ_W 228
int gI(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int gI_alloc_mem(void);
int gI_init_mem(int mem);
void gI_free_mem(int mem);
int gI_checkout(void);
void gI_release(int mem);
void gI_incref(void);
void gI_decref(void);
casadi_int gI_n_in(void);
casadi_int gI_n_out(void);
casadi_real gI_default_in(casadi_int i);
const char* gI_name_in(casadi_int i);
const char* gI_name_out(casadi_int i);
const casadi_int* gI_sparsity_in(casadi_int i);
const casadi_int* gI_sparsity_out(casadi_int i);
int gI_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int gI_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define gI_SZ_ARG 15
#define gI_SZ_RES 2
#define gI_SZ_IW 0
#define gI_SZ_W 39
int Ggt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int Ggt_alloc_mem(void);
int Ggt_init_mem(int mem);
void Ggt_free_mem(int mem);
int Ggt_checkout(void);
void Ggt_release(int mem);
void Ggt_incref(void);
void Ggt_decref(void);
casadi_int Ggt_n_in(void);
casadi_int Ggt_n_out(void);
casadi_real Ggt_default_in(casadi_int i);
const char* Ggt_name_in(casadi_int i);
const char* Ggt_name_out(casadi_int i);
const casadi_int* Ggt_sparsity_in(casadi_int i);
const casadi_int* Ggt_sparsity_out(casadi_int i);
int Ggt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int Ggt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define Ggt_SZ_ARG 4
#define Ggt_SZ_RES 1
#define Ggt_SZ_IW 0
#define Ggt_SZ_W 0
int g(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int g_alloc_mem(void);
int g_init_mem(int mem);
void g_free_mem(int mem);
int g_checkout(void);
void g_release(int mem);
void g_incref(void);
void g_decref(void);
casadi_int g_n_in(void);
casadi_int g_n_out(void);
casadi_real g_default_in(casadi_int i);
const char* g_name_in(casadi_int i);
const char* g_name_out(casadi_int i);
const casadi_int* g_sparsity_in(casadi_int i);
const casadi_int* g_sparsity_out(casadi_int i);
int g_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int g_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define g_SZ_ARG 4
#define g_SZ_RES 1
#define g_SZ_IW 0
#define g_SZ_W 0
int GgtF(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int GgtF_alloc_mem(void);
int GgtF_init_mem(int mem);
void GgtF_free_mem(int mem);
int GgtF_checkout(void);
void GgtF_release(int mem);
void GgtF_incref(void);
void GgtF_decref(void);
casadi_int GgtF_n_in(void);
casadi_int GgtF_n_out(void);
casadi_real GgtF_default_in(casadi_int i);
const char* GgtF_name_in(casadi_int i);
const char* GgtF_name_out(casadi_int i);
const casadi_int* GgtF_sparsity_in(casadi_int i);
const casadi_int* GgtF_sparsity_out(casadi_int i);
int GgtF_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int GgtF_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define GgtF_SZ_ARG 4
#define GgtF_SZ_RES 1
#define GgtF_SZ_IW 0
#define GgtF_SZ_W 0
int gF(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int gF_alloc_mem(void);
int gF_init_mem(int mem);
void gF_free_mem(int mem);
int gF_checkout(void);
void gF_release(int mem);
void gF_incref(void);
void gF_decref(void);
casadi_int gF_n_in(void);
casadi_int gF_n_out(void);
casadi_real gF_default_in(casadi_int i);
const char* gF_name_in(casadi_int i);
const char* gF_name_out(casadi_int i);
const casadi_int* gF_sparsity_in(casadi_int i);
const casadi_int* gF_sparsity_out(casadi_int i);
int gF_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int gF_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define gF_SZ_ARG 4
#define gF_SZ_RES 1
#define gF_SZ_IW 0
#define gF_SZ_W 0
int GgineqIt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int GgineqIt_alloc_mem(void);
int GgineqIt_init_mem(int mem);
void GgineqIt_free_mem(int mem);
int GgineqIt_checkout(void);
void GgineqIt_release(int mem);
void GgineqIt_incref(void);
void GgineqIt_decref(void);
casadi_int GgineqIt_n_in(void);
casadi_int GgineqIt_n_out(void);
casadi_real GgineqIt_default_in(casadi_int i);
const char* GgineqIt_name_in(casadi_int i);
const char* GgineqIt_name_out(casadi_int i);
const casadi_int* GgineqIt_sparsity_in(casadi_int i);
const casadi_int* GgineqIt_sparsity_out(casadi_int i);
int GgineqIt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int GgineqIt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define GgineqIt_SZ_ARG 6
#define GgineqIt_SZ_RES 9
#define GgineqIt_SZ_IW 0
#define GgineqIt_SZ_W 51
int gineqI(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int gineqI_alloc_mem(void);
int gineqI_init_mem(int mem);
void gineqI_free_mem(int mem);
int gineqI_checkout(void);
void gineqI_release(int mem);
void gineqI_incref(void);
void gineqI_decref(void);
casadi_int gineqI_n_in(void);
casadi_int gineqI_n_out(void);
casadi_real gineqI_default_in(casadi_int i);
const char* gineqI_name_in(casadi_int i);
const char* gineqI_name_out(casadi_int i);
const casadi_int* gineqI_sparsity_in(casadi_int i);
const casadi_int* gineqI_sparsity_out(casadi_int i);
int gineqI_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int gineqI_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define gineqI_SZ_ARG 4
#define gineqI_SZ_RES 2
#define gineqI_SZ_IW 0
#define gineqI_SZ_W 1
int Ggineqt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int Ggineqt_alloc_mem(void);
int Ggineqt_init_mem(int mem);
void Ggineqt_free_mem(int mem);
int Ggineqt_checkout(void);
void Ggineqt_release(int mem);
void Ggineqt_incref(void);
void Ggineqt_decref(void);
casadi_int Ggineqt_n_in(void);
casadi_int Ggineqt_n_out(void);
casadi_real Ggineqt_default_in(casadi_int i);
const char* Ggineqt_name_in(casadi_int i);
const char* Ggineqt_name_out(casadi_int i);
const casadi_int* Ggineqt_sparsity_in(casadi_int i);
const casadi_int* Ggineqt_sparsity_out(casadi_int i);
int Ggineqt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int Ggineqt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define Ggineqt_SZ_ARG 6
#define Ggineqt_SZ_RES 9
#define Ggineqt_SZ_IW 0
#define Ggineqt_SZ_W 51
int gineq(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int gineq_alloc_mem(void);
int gineq_init_mem(int mem);
void gineq_free_mem(int mem);
int gineq_checkout(void);
void gineq_release(int mem);
void gineq_incref(void);
void gineq_decref(void);
casadi_int gineq_n_in(void);
casadi_int gineq_n_out(void);
casadi_real gineq_default_in(casadi_int i);
const char* gineq_name_in(casadi_int i);
const char* gineq_name_out(casadi_int i);
const casadi_int* gineq_sparsity_in(casadi_int i);
const casadi_int* gineq_sparsity_out(casadi_int i);
int gineq_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int gineq_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define gineq_SZ_ARG 4
#define gineq_SZ_RES 2
#define gineq_SZ_IW 0
#define gineq_SZ_W 1
int GgineqFt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int GgineqFt_alloc_mem(void);
int GgineqFt_init_mem(int mem);
void GgineqFt_free_mem(int mem);
int GgineqFt_checkout(void);
void GgineqFt_release(int mem);
void GgineqFt_incref(void);
void GgineqFt_decref(void);
casadi_int GgineqFt_n_in(void);
casadi_int GgineqFt_n_out(void);
casadi_real GgineqFt_default_in(casadi_int i);
const char* GgineqFt_name_in(casadi_int i);
const char* GgineqFt_name_out(casadi_int i);
const casadi_int* GgineqFt_sparsity_in(casadi_int i);
const casadi_int* GgineqFt_sparsity_out(casadi_int i);
int GgineqFt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int GgineqFt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define GgineqFt_SZ_ARG 3
#define GgineqFt_SZ_RES 1
#define GgineqFt_SZ_IW 0
#define GgineqFt_SZ_W 0
int gineqF(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int gineqF_alloc_mem(void);
int gineqF_init_mem(int mem);
void gineqF_free_mem(int mem);
int gineqF_checkout(void);
void gineqF_release(int mem);
void gineqF_incref(void);
void gineqF_decref(void);
casadi_int gineqF_n_in(void);
casadi_int gineqF_n_out(void);
casadi_real gineqF_default_in(casadi_int i);
const char* gineqF_name_in(casadi_int i);
const char* gineqF_name_out(casadi_int i);
const casadi_int* gineqF_sparsity_in(casadi_int i);
const casadi_int* gineqF_sparsity_out(casadi_int i);
int gineqF_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int gineqF_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define gineqF_SZ_ARG 3
#define gineqF_SZ_RES 1
#define gineqF_SZ_IW 0
#define gineqF_SZ_W 0
int sampler_xe(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int sampler_xe_alloc_mem(void);
int sampler_xe_init_mem(int mem);
void sampler_xe_free_mem(int mem);
int sampler_xe_checkout(void);
void sampler_xe_release(int mem);
void sampler_xe_incref(void);
void sampler_xe_decref(void);
casadi_int sampler_xe_n_in(void);
casadi_int sampler_xe_n_out(void);
casadi_real sampler_xe_default_in(casadi_int i);
const char* sampler_xe_name_in(casadi_int i);
const char* sampler_xe_name_out(casadi_int i);
const casadi_int* sampler_xe_sparsity_in(casadi_int i);
const casadi_int* sampler_xe_sparsity_out(casadi_int i);
int sampler_xe_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int sampler_xe_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define sampler_xe_SZ_ARG 6
#define sampler_xe_SZ_RES 2
#define sampler_xe_SZ_IW 0
#define sampler_xe_SZ_W 8
int sampler_ye(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int sampler_ye_alloc_mem(void);
int sampler_ye_init_mem(int mem);
void sampler_ye_free_mem(int mem);
int sampler_ye_checkout(void);
void sampler_ye_release(int mem);
void sampler_ye_incref(void);
void sampler_ye_decref(void);
casadi_int sampler_ye_n_in(void);
casadi_int sampler_ye_n_out(void);
casadi_real sampler_ye_default_in(casadi_int i);
const char* sampler_ye_name_in(casadi_int i);
const char* sampler_ye_name_out(casadi_int i);
const casadi_int* sampler_ye_sparsity_in(casadi_int i);
const casadi_int* sampler_ye_sparsity_out(casadi_int i);
int sampler_ye_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int sampler_ye_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define sampler_ye_SZ_ARG 6
#define sampler_ye_SZ_RES 2
#define sampler_ye_SZ_IW 0
#define sampler_ye_SZ_W 8
int sampler_psie(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int sampler_psie_alloc_mem(void);
int sampler_psie_init_mem(int mem);
void sampler_psie_free_mem(int mem);
int sampler_psie_checkout(void);
void sampler_psie_release(int mem);
void sampler_psie_incref(void);
void sampler_psie_decref(void);
casadi_int sampler_psie_n_in(void);
casadi_int sampler_psie_n_out(void);
casadi_real sampler_psie_default_in(casadi_int i);
const char* sampler_psie_name_in(casadi_int i);
const char* sampler_psie_name_out(casadi_int i);
const casadi_int* sampler_psie_sparsity_in(casadi_int i);
const casadi_int* sampler_psie_sparsity_out(casadi_int i);
int sampler_psie_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int sampler_psie_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define sampler_psie_SZ_ARG 6
#define sampler_psie_SZ_RES 2
#define sampler_psie_SZ_IW 0
#define sampler_psie_SZ_W 4
int sampler_gamma_p(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int sampler_gamma_p_alloc_mem(void);
int sampler_gamma_p_init_mem(int mem);
void sampler_gamma_p_free_mem(int mem);
int sampler_gamma_p_checkout(void);
void sampler_gamma_p_release(int mem);
void sampler_gamma_p_incref(void);
void sampler_gamma_p_decref(void);
casadi_int sampler_gamma_p_n_in(void);
casadi_int sampler_gamma_p_n_out(void);
casadi_real sampler_gamma_p_default_in(casadi_int i);
const char* sampler_gamma_p_name_in(casadi_int i);
const char* sampler_gamma_p_name_out(casadi_int i);
const casadi_int* sampler_gamma_p_sparsity_in(casadi_int i);
const casadi_int* sampler_gamma_p_sparsity_out(casadi_int i);
int sampler_gamma_p_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int sampler_gamma_p_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define sampler_gamma_p_SZ_ARG 4
#define sampler_gamma_p_SZ_RES 2
#define sampler_gamma_p_SZ_IW 0
#define sampler_gamma_p_SZ_W 1
int sampler_obs_cost(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int sampler_obs_cost_alloc_mem(void);
int sampler_obs_cost_init_mem(int mem);
void sampler_obs_cost_free_mem(int mem);
int sampler_obs_cost_checkout(void);
void sampler_obs_cost_release(int mem);
void sampler_obs_cost_incref(void);
void sampler_obs_cost_decref(void);
casadi_int sampler_obs_cost_n_in(void);
casadi_int sampler_obs_cost_n_out(void);
casadi_real sampler_obs_cost_default_in(casadi_int i);
const char* sampler_obs_cost_name_in(casadi_int i);
const char* sampler_obs_cost_name_out(casadi_int i);
const casadi_int* sampler_obs_cost_sparsity_in(casadi_int i);
const casadi_int* sampler_obs_cost_sparsity_out(casadi_int i);
int sampler_obs_cost_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int sampler_obs_cost_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define sampler_obs_cost_SZ_ARG 6
#define sampler_obs_cost_SZ_RES 2
#define sampler_obs_cost_SZ_IW 0
#define sampler_obs_cost_SZ_W 12
int sampler_n_horizon(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int sampler_n_horizon_alloc_mem(void);
int sampler_n_horizon_init_mem(int mem);
void sampler_n_horizon_free_mem(int mem);
int sampler_n_horizon_checkout(void);
void sampler_n_horizon_release(int mem);
void sampler_n_horizon_incref(void);
void sampler_n_horizon_decref(void);
casadi_int sampler_n_horizon_n_in(void);
casadi_int sampler_n_horizon_n_out(void);
casadi_real sampler_n_horizon_default_in(casadi_int i);
const char* sampler_n_horizon_name_in(casadi_int i);
const char* sampler_n_horizon_name_out(casadi_int i);
const casadi_int* sampler_n_horizon_sparsity_in(casadi_int i);
const casadi_int* sampler_n_horizon_sparsity_out(casadi_int i);
int sampler_n_horizon_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int sampler_n_horizon_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define sampler_n_horizon_SZ_ARG 4
#define sampler_n_horizon_SZ_RES 2
#define sampler_n_horizon_SZ_IW 0
#define sampler_n_horizon_SZ_W 1
#ifdef __cplusplus
} /* extern "C" */
#endif
