g1_red:
  x: 3.0
  y: 2.5
  color: red
  type: round
g1_green:
  x: 3.0
  y: -2.0
  color: green
  type: round

g2_red:
  x: 14.0
  y: 3.0
  color: red
  type: round
g2_green:
  x: 15.0
  y: -1.0
  color: green
  type: round