#!/bin/bash

# Check if at least 1 argument is provided
if [ $# -lt 1 ]; then
    echo "Error: At least one argument is required."
    echo "Usage: $0 arg1 [arg2] [arg3]"
    exit 1
fi

# Assign default values if arguments are missing
arg1=$1
arg2=${2:-$1}  # Default to arg1 if arg2 is not provided
arg3=${3:-$1}

ros2 param set /clustering_segmentation voxel_grid_x $arg1
ros2 param set /clustering_segmentation voxel_grid_y $arg2
ros2 param set /clustering_segmentation voxel_grid_z $arg3
