/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) usv_model_guidance5_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_project CASADI_PREFIX(project)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_project(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, const casadi_int* sp_y, casadi_real* w) {
  casadi_int ncol_x, ncol_y, i, el;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  for (i=0; i<ncol_x; ++i) {
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) w[row_y[el]] = 0;
    for (el=colind_x[i]; el<colind_x[i+1]; ++el) w[row_x[el]] = x[el];
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) y[el] = w[row_y[el]];
  }
}

static const casadi_int casadi_s0[5] = {5, 1, 0, 1, 4};
static const casadi_int casadi_s1[7] = {5, 1, 0, 3, 2, 3, 4};
static const casadi_int casadi_s2[6] = {5, 1, 0, 2, 2, 3};
static const casadi_int casadi_s3[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s4[33] = {5, 5, 0, 5, 10, 15, 20, 25, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4};
static const casadi_int casadi_s5[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s6[3] = {0, 0, 0};
static const casadi_int casadi_s7[18] = {5, 5, 0, 2, 4, 6, 8, 10, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3};

/* usv_model_guidance5_expl_vde_forw:(i0[5],i1[5x5],i2[5],i3,i4[])->(o0[5],o1[5x5,10nz],o2[5x1,3nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7, *w8=w+13, *w9=w+38, *w10=w+43, *w11=w+48, *w12=w+53, *w13=w+58, w14, w15, w16, w17, w18, w19, w20, w21, *w22=w+71, *w26=w+74, *w27=w+76;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #2: @0 = 0 */
  w0 = 0.;
  /* #3: output[0][1] = @0 */
  if (res[0]) res[0][1] = w0;
  /* #4: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #5: @1 = input[0][3] */
  w1 = arg[0] ? arg[0][3] : 0;
  /* #6: @2 = input[0][1] */
  w2 = arg[0] ? arg[0][1] : 0;
  /* #7: @3 = 0.001 */
  w3 = 1.0000000000000000e-03;
  /* #8: @3 = (@3+@0) */
  w3 += w0;
  /* #9: @4 = atan2(@2,@3) */
  w4  = atan2(w2,w3);
  /* #10: @1 = (@1-@4) */
  w1 -= w4;
  /* #11: @4 = sin(@1) */
  w4 = sin( w1 );
  /* #12: @5 = (@0*@4) */
  w5  = (w0*w4);
  /* #13: @6 = cos(@1) */
  w6 = cos( w1 );
  /* #14: @7 = (@2*@6) */
  w7  = (w2*w6);
  /* #15: @5 = (@5+@7) */
  w5 += w7;
  /* #16: output[0][2] = @5 */
  if (res[0]) res[0][2] = w5;
  /* #17: @5 = input[0][4] */
  w5 = arg[0] ? arg[0][4] : 0;
  /* #18: @5 = (@5-@1) */
  w5 -= w1;
  /* #19: output[0][3] = @5 */
  if (res[0]) res[0][3] = w5;
  /* #20: @5 = input[3][0] */
  w5 = arg[3] ? arg[3][0] : 0;
  /* #21: output[0][4] = @5 */
  if (res[0]) res[0][4] = w5;
  /* #22: @8 = input[1][0] */
  casadi_copy(arg[1], 25, w8);
  /* #23: {@9, @10, @11, @12, @13} = horzsplit(@8) */
  casadi_copy(w8, 5, w9);
  casadi_copy(w8+5, 5, w10);
  casadi_copy(w8+10, 5, w11);
  casadi_copy(w8+15, 5, w12);
  casadi_copy(w8+20, 5, w13);
  /* #24: {@5, @7, NULL, @14, @15} = vertsplit(@9) */
  w5 = w9[0];
  w7 = w9[1];
  w14 = w9[3];
  w15 = w9[4];
  /* #25: @16 = (@4*@5) */
  w16  = (w4*w5);
  /* #26: @17 = cos(@1) */
  w17 = cos( w1 );
  /* #27: @18 = sq(@2) */
  w18 = casadi_sq( w2 );
  /* #28: @19 = sq(@3) */
  w19 = casadi_sq( w3 );
  /* #29: @18 = (@18+@19) */
  w18 += w19;
  /* #30: @19 = (@3/@18) */
  w19  = (w3/w18);
  /* #31: @20 = (@19*@7) */
  w20  = (w19*w7);
  /* #32: @18 = (@2/@18) */
  w18  = (w2/w18);
  /* #33: @5 = (@18*@5) */
  w5  = (w18*w5);
  /* #34: @20 = (@20-@5) */
  w20 -= w5;
  /* #35: @14 = (@14-@20) */
  w14 -= w20;
  /* #36: @20 = (@17*@14) */
  w20  = (w17*w14);
  /* #37: @20 = (@0*@20) */
  w20  = (w0*w20);
  /* #38: @16 = (@16+@20) */
  w16 += w20;
  /* #39: @7 = (@6*@7) */
  w7  = (w6*w7);
  /* #40: @20 = sin(@1) */
  w20 = sin( w1 );
  /* #41: @5 = (@20*@14) */
  w5  = (w20*w14);
  /* #42: @5 = (@2*@5) */
  w5  = (w2*w5);
  /* #43: @7 = (@7-@5) */
  w7 -= w5;
  /* #44: @16 = (@16+@7) */
  w16 += w7;
  /* #45: output[1][0] = @16 */
  if (res[1]) res[1][0] = w16;
  /* #46: @15 = (@15-@14) */
  w15 -= w14;
  /* #47: output[1][1] = @15 */
  if (res[1]) res[1][1] = w15;
  /* #48: {@15, @14, NULL, @16, @7} = vertsplit(@10) */
  w15 = w10[0];
  w14 = w10[1];
  w16 = w10[3];
  w7 = w10[4];
  /* #49: @5 = (@4*@15) */
  w5  = (w4*w15);
  /* #50: @21 = (@19*@14) */
  w21  = (w19*w14);
  /* #51: @15 = (@18*@15) */
  w15  = (w18*w15);
  /* #52: @21 = (@21-@15) */
  w21 -= w15;
  /* #53: @16 = (@16-@21) */
  w16 -= w21;
  /* #54: @21 = (@17*@16) */
  w21  = (w17*w16);
  /* #55: @21 = (@0*@21) */
  w21  = (w0*w21);
  /* #56: @5 = (@5+@21) */
  w5 += w21;
  /* #57: @14 = (@6*@14) */
  w14  = (w6*w14);
  /* #58: @21 = (@20*@16) */
  w21  = (w20*w16);
  /* #59: @21 = (@2*@21) */
  w21  = (w2*w21);
  /* #60: @14 = (@14-@21) */
  w14 -= w21;
  /* #61: @5 = (@5+@14) */
  w5 += w14;
  /* #62: output[1][2] = @5 */
  if (res[1]) res[1][2] = w5;
  /* #63: @7 = (@7-@16) */
  w7 -= w16;
  /* #64: output[1][3] = @7 */
  if (res[1]) res[1][3] = w7;
  /* #65: {@7, @16, NULL, @5, @14} = vertsplit(@11) */
  w7 = w11[0];
  w16 = w11[1];
  w5 = w11[3];
  w14 = w11[4];
  /* #66: @21 = (@4*@7) */
  w21  = (w4*w7);
  /* #67: @15 = (@19*@16) */
  w15  = (w19*w16);
  /* #68: @7 = (@18*@7) */
  w7  = (w18*w7);
  /* #69: @15 = (@15-@7) */
  w15 -= w7;
  /* #70: @5 = (@5-@15) */
  w5 -= w15;
  /* #71: @15 = (@17*@5) */
  w15  = (w17*w5);
  /* #72: @15 = (@0*@15) */
  w15  = (w0*w15);
  /* #73: @21 = (@21+@15) */
  w21 += w15;
  /* #74: @16 = (@6*@16) */
  w16  = (w6*w16);
  /* #75: @15 = (@20*@5) */
  w15  = (w20*w5);
  /* #76: @15 = (@2*@15) */
  w15  = (w2*w15);
  /* #77: @16 = (@16-@15) */
  w16 -= w15;
  /* #78: @21 = (@21+@16) */
  w21 += w16;
  /* #79: output[1][4] = @21 */
  if (res[1]) res[1][4] = w21;
  /* #80: @14 = (@14-@5) */
  w14 -= w5;
  /* #81: output[1][5] = @14 */
  if (res[1]) res[1][5] = w14;
  /* #82: {@14, @5, NULL, @21, @16} = vertsplit(@12) */
  w14 = w12[0];
  w5 = w12[1];
  w21 = w12[3];
  w16 = w12[4];
  /* #83: @15 = (@4*@14) */
  w15  = (w4*w14);
  /* #84: @7 = (@19*@5) */
  w7  = (w19*w5);
  /* #85: @14 = (@18*@14) */
  w14  = (w18*w14);
  /* #86: @7 = (@7-@14) */
  w7 -= w14;
  /* #87: @21 = (@21-@7) */
  w21 -= w7;
  /* #88: @7 = (@17*@21) */
  w7  = (w17*w21);
  /* #89: @7 = (@0*@7) */
  w7  = (w0*w7);
  /* #90: @15 = (@15+@7) */
  w15 += w7;
  /* #91: @5 = (@6*@5) */
  w5  = (w6*w5);
  /* #92: @7 = (@20*@21) */
  w7  = (w20*w21);
  /* #93: @7 = (@2*@7) */
  w7  = (w2*w7);
  /* #94: @5 = (@5-@7) */
  w5 -= w7;
  /* #95: @15 = (@15+@5) */
  w15 += w5;
  /* #96: output[1][6] = @15 */
  if (res[1]) res[1][6] = w15;
  /* #97: @16 = (@16-@21) */
  w16 -= w21;
  /* #98: output[1][7] = @16 */
  if (res[1]) res[1][7] = w16;
  /* #99: {@16, @21, NULL, @15, @5} = vertsplit(@13) */
  w16 = w13[0];
  w21 = w13[1];
  w15 = w13[3];
  w5 = w13[4];
  /* #100: @7 = (@4*@16) */
  w7  = (w4*w16);
  /* #101: @19 = (@19*@21) */
  w19 *= w21;
  /* #102: @18 = (@18*@16) */
  w18 *= w16;
  /* #103: @19 = (@19-@18) */
  w19 -= w18;
  /* #104: @15 = (@15-@19) */
  w15 -= w19;
  /* #105: @17 = (@17*@15) */
  w17 *= w15;
  /* #106: @17 = (@0*@17) */
  w17  = (w0*w17);
  /* #107: @7 = (@7+@17) */
  w7 += w17;
  /* #108: @21 = (@6*@21) */
  w21  = (w6*w21);
  /* #109: @20 = (@20*@15) */
  w20 *= w15;
  /* #110: @20 = (@2*@20) */
  w20  = (w2*w20);
  /* #111: @21 = (@21-@20) */
  w21 -= w20;
  /* #112: @7 = (@7+@21) */
  w7 += w21;
  /* #113: output[1][8] = @7 */
  if (res[1]) res[1][8] = w7;
  /* #114: @5 = (@5-@15) */
  w5 -= w15;
  /* #115: output[1][9] = @5 */
  if (res[1]) res[1][9] = w5;
  /* #116: @5 = zeros(1x5,1nz) */
  w5 = 0.;
  /* #117: @15 = 1 */
  w15 = 1.;
  /* #118: (@5[0] = @15) */
  for (rr=(&w5)+0, ss=(&w15); rr!=(&w5)+1; rr+=1) *rr = *ss++;
  /* #119: @5 = @5' */
  /* #120: @22 = project(@5) */
  casadi_project((&w5), casadi_s0, w22, casadi_s1, w);
  /* #121: @23 = 00 */
  /* #122: @24 = 00 */
  /* #123: @13 = input[2][0] */
  casadi_copy(arg[2], 5, w13);
  /* #124: {@5, @15, NULL, @7, @21} = vertsplit(@13) */
  w5 = w13[0];
  w15 = w13[1];
  w7 = w13[3];
  w21 = w13[4];
  /* #125: @4 = (@4*@5) */
  w4 *= w5;
  /* #126: @20 = cos(@1) */
  w20 = cos( w1 );
  /* #127: @17 = sq(@2) */
  w17 = casadi_sq( w2 );
  /* #128: @19 = sq(@3) */
  w19 = casadi_sq( w3 );
  /* #129: @17 = (@17+@19) */
  w17 += w19;
  /* #130: @3 = (@3/@17) */
  w3 /= w17;
  /* #131: @3 = (@3*@15) */
  w3 *= w15;
  /* #132: @17 = (@2/@17) */
  w17  = (w2/w17);
  /* #133: @17 = (@17*@5) */
  w17 *= w5;
  /* #134: @3 = (@3-@17) */
  w3 -= w17;
  /* #135: @7 = (@7-@3) */
  w7 -= w3;
  /* #136: @20 = (@20*@7) */
  w20 *= w7;
  /* #137: @0 = (@0*@20) */
  w0 *= w20;
  /* #138: @4 = (@4+@0) */
  w4 += w0;
  /* #139: @6 = (@6*@15) */
  w6 *= w15;
  /* #140: @1 = sin(@1) */
  w1 = sin( w1 );
  /* #141: @1 = (@1*@7) */
  w1 *= w7;
  /* #142: @2 = (@2*@1) */
  w2 *= w1;
  /* #143: @6 = (@6-@2) */
  w6 -= w2;
  /* #144: @4 = (@4+@6) */
  w4 += w6;
  /* #145: @21 = (@21-@7) */
  w21 -= w7;
  /* #146: @25 = 00 */
  /* #147: @26 = vertcat(@23, @24, @4, @21, @25) */
  rr=w26;
  *rr++ = w4;
  *rr++ = w21;
  /* #148: @27 = project(@26) */
  casadi_project(w26, casadi_s2, w27, casadi_s1, w);
  /* #149: @22 = (@22+@27) */
  for (i=0, rr=w22, cs=w27; i<3; ++i) (*rr++) += (*cs++);
  /* #150: output[2][0] = @22 */
  casadi_copy(w22, 3, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int usv_model_guidance5_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int usv_model_guidance5_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int usv_model_guidance5_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void usv_model_guidance5_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int usv_model_guidance5_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void usv_model_guidance5_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void usv_model_guidance5_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void usv_model_guidance5_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int usv_model_guidance5_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int usv_model_guidance5_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real usv_model_guidance5_expl_vde_forw_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* usv_model_guidance5_expl_vde_forw_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* usv_model_guidance5_expl_vde_forw_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* usv_model_guidance5_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s4;
    case 2: return casadi_s3;
    case 3: return casadi_s5;
    case 4: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* usv_model_guidance5_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s7;
    case 2: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int usv_model_guidance5_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10;
  if (sz_res) *sz_res = 8;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 79;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
