/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) usv_model_guidance5_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s1[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[9] = {6, 1, 0, 5, 0, 1, 3, 4, 5};

/* usv_model_guidance5_expl_vde_adj:(i0[5],i1[5],i2,i3[])->(o0[6x1,5nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3, w4, *w5=w+5, w6, w7, w8, w9, w10, w11;
  /* #0: @0 = input[0][3] */
  w0 = arg[0] ? arg[0][3] : 0;
  /* #1: @1 = input[0][1] */
  w1 = arg[0] ? arg[0][1] : 0;
  /* #2: @2 = 0.001 */
  w2 = 1.0000000000000000e-03;
  /* #3: @3 = input[0][0] */
  w3 = arg[0] ? arg[0][0] : 0;
  /* #4: @2 = (@2+@3) */
  w2 += w3;
  /* #5: @4 = atan2(@1,@2) */
  w4  = atan2(w1,w2);
  /* #6: @0 = (@0-@4) */
  w0 -= w4;
  /* #7: @4 = sin(@0) */
  w4 = sin( w0 );
  /* #8: @5 = input[1][0] */
  casadi_copy(arg[1], 5, w5);
  /* #9: {NULL, NULL, @6, @7, @8} = vertsplit(@5) */
  w6 = w5[2];
  w7 = w5[3];
  w8 = w5[4];
  /* #10: @4 = (@4*@6) */
  w4 *= w6;
  /* #11: @9 = sq(@1) */
  w9 = casadi_sq( w1 );
  /* #12: @10 = sq(@2) */
  w10 = casadi_sq( w2 );
  /* #13: @9 = (@9+@10) */
  w9 += w10;
  /* #14: @10 = (@1/@9) */
  w10  = (w1/w9);
  /* #15: @11 = sin(@0) */
  w11 = sin( w0 );
  /* #16: @1 = (@1*@6) */
  w1 *= w6;
  /* #17: @11 = (@11*@1) */
  w11 *= w1;
  /* #18: @11 = (-@11) */
  w11 = (- w11 );
  /* #19: @11 = (@11-@7) */
  w11 -= w7;
  /* #20: @1 = cos(@0) */
  w1 = cos( w0 );
  /* #21: @3 = (@3*@6) */
  w3 *= w6;
  /* #22: @1 = (@1*@3) */
  w1 *= w3;
  /* #23: @11 = (@11+@1) */
  w11 += w1;
  /* #24: @10 = (@10*@11) */
  w10 *= w11;
  /* #25: @4 = (@4+@10) */
  w4 += w10;
  /* #26: output[0][0] = @4 */
  if (res[0]) res[0][0] = w4;
  /* #27: @0 = cos(@0) */
  w0 = cos( w0 );
  /* #28: @0 = (@0*@6) */
  w0 *= w6;
  /* #29: @2 = (@2/@9) */
  w2 /= w9;
  /* #30: @2 = (@2*@11) */
  w2 *= w11;
  /* #31: @0 = (@0-@2) */
  w0 -= w2;
  /* #32: output[0][1] = @0 */
  if (res[0]) res[0][1] = w0;
  /* #33: output[0][2] = @11 */
  if (res[0]) res[0][2] = w11;
  /* #34: output[0][3] = @7 */
  if (res[0]) res[0][3] = w7;
  /* #35: output[0][4] = @8 */
  if (res[0]) res[0][4] = w8;
  return 0;
}

CASADI_SYMBOL_EXPORT int usv_model_guidance5_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int usv_model_guidance5_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int usv_model_guidance5_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void usv_model_guidance5_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int usv_model_guidance5_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void usv_model_guidance5_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void usv_model_guidance5_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void usv_model_guidance5_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int usv_model_guidance5_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int usv_model_guidance5_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real usv_model_guidance5_expl_vde_adj_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* usv_model_guidance5_expl_vde_adj_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* usv_model_guidance5_expl_vde_adj_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* usv_model_guidance5_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* usv_model_guidance5_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int usv_model_guidance5_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 6;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 16;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
