/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) usv_model_pf_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[18] = {14, 1, 0, 14, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[3] = {0, 0, 0};

/* usv_model_pf_expl_ode_fun:(i0[14],i1[2],i2[])->(o0[14]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10;
  /* #0: @0 = input[0][5] */
  w0 = arg[0] ? arg[0][5] : 0;
  /* #1: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #2: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #3: @2 = input[0][4] */
  w2 = arg[0] ? arg[0][4] : 0;
  /* #4: @3 = 0.001 */
  w3 = 1.0000000000000000e-03;
  /* #5: @4 = input[0][3] */
  w4 = arg[0] ? arg[0][3] : 0;
  /* #6: @3 = (@3+@4) */
  w3 += w4;
  /* #7: @3 = atan2(@2,@3) */
  w3  = atan2(w2,w3);
  /* #8: @3 = (@1+@3) */
  w3  = (w1+w3);
  /* #9: @5 = cos(@3) */
  w5 = cos( w3 );
  /* #10: @5 = (@5*@0) */
  w5 *= w0;
  /* #11: output[0][1] = @5 */
  if (res[0]) res[0][1] = w5;
  /* #12: @3 = sin(@3) */
  w3 = sin( w3 );
  /* #13: @3 = (@3*@0) */
  w3 *= w0;
  /* #14: @3 = (-@3) */
  w3 = (- w3 );
  /* #15: output[0][2] = @3 */
  if (res[0]) res[0][2] = w3;
  /* #16: @3 = input[0][12] */
  w3 = arg[0] ? arg[0][12] : 0;
  /* #17: @5 = input[0][13] */
  w5 = arg[0] ? arg[0][13] : 0;
  /* #18: @6 = (@3+@5) */
  w6  = (w3+w5);
  /* #19: @7 = -76.26 */
  w7 = -7.6259999999999991e+01;
  /* #20: @7 = (@7*@2) */
  w7 *= w2;
  /* #21: @6 = (@6-@7) */
  w6 -= w7;
  /* #22: @7 = -17.72 */
  w7 = -1.7719999999999999e+01;
  /* #23: @7 = (@7*@0) */
  w7 *= w0;
  /* #24: @7 = (@7*@0) */
  w7 *= w0;
  /* #25: @6 = (@6-@7) */
  w6 -= w7;
  /* #26: @7 = 1.25 */
  w7 = 1.2500000000000000e+00;
  /* #27: @7 = (@7<@4) */
  w7  = (w7<w4);
  /* #28: @8 = 64.55 */
  w8 = 6.4549999999999997e+01;
  /* #29: @8 = (@7?@8:0) */
  w8  = (w7?w8:0);
  /* #30: @7 = (!@7) */
  w7 = (! w7 );
  /* #31: @9 = -25 */
  w9 = -25.;
  /* #32: @7 = (@7?@9:0) */
  w7  = (w7?w9:0);
  /* #33: @8 = (@8+@7) */
  w8 += w7;
  /* #34: @8 = (@8*@4) */
  w8 *= w4;
  /* #35: @8 = (-@8) */
  w8 = (- w8 );
  /* #36: @7 = 1.25 */
  w7 = 1.2500000000000000e+00;
  /* #37: @7 = (@7<@4) */
  w7  = (w7<w4);
  /* #38: @9 = -70.92 */
  w9 = -7.0920000000000002e+01;
  /* #39: @7 = (@7?@9:0) */
  w7  = (w7?w9:0);
  /* #40: @9 = fabs(@4) */
  w9 = fabs( w4 );
  /* #41: @7 = (@7*@9) */
  w7 *= w9;
  /* #42: @7 = (@7*@4) */
  w7 *= w4;
  /* #43: @8 = (@8-@7) */
  w8 -= w7;
  /* #44: @6 = (@6-@8) */
  w6 -= w8;
  /* #45: @8 = 32.25 */
  w8 = 3.2250000000000000e+01;
  /* #46: @6 = (@6/@8) */
  w6 /= w8;
  /* #47: output[0][3] = @6 */
  if (res[0]) res[0][3] = w6;
  /* #48: @6 = -32.25 */
  w6 = -3.2250000000000000e+01;
  /* #49: @6 = (@6*@4) */
  w6 *= w4;
  /* #50: @6 = (@6*@0) */
  w6 *= w0;
  /* #51: @8 = 0.9945 */
  w8 = 9.9450000000000016e-01;
  /* #52: @7 = 0.5 */
  w7 = 5.0000000000000000e-01;
  /* #53: @9 = -40000 */
  w9 = -40000.;
  /* #54: @10 = fabs(@2) */
  w10 = fabs( w2 );
  /* #55: @9 = (@9*@10) */
  w9 *= w10;
  /* #56: @7 = (@7*@9) */
  w7 *= w9;
  /* #57: @8 = (@8*@7) */
  w8 *= w7;
  /* #58: @8 = (-@8) */
  w8 = (- w8 );
  /* #59: @7 = -99.99 */
  w7 = -9.9989999999999995e+01;
  /* #60: @9 = fabs(@2) */
  w9 = fabs( w2 );
  /* #61: @7 = (@7*@9) */
  w7 *= w9;
  /* #62: @8 = (@8-@7) */
  w8 -= w7;
  /* #63: @7 = -5.49 */
  w7 = -5.4900000000000002e+00;
  /* #64: @9 = fabs(@0) */
  w9 = fabs( w0 );
  /* #65: @7 = (@7*@9) */
  w7 *= w9;
  /* #66: @8 = (@8-@7) */
  w8 -= w7;
  /* #67: @8 = (@8*@2) */
  w8 *= w2;
  /* #68: @6 = (@6-@8) */
  w6 -= w8;
  /* #69: @8 = 53.13 */
  w8 = 5.3129999999999995e+01;
  /* #70: @6 = (@6/@8) */
  w6 /= w8;
  /* #71: output[0][4] = @6 */
  if (res[0]) res[0][4] = w6;
  /* #72: @6 = 0.41 */
  w6 = 4.0999999999999998e-01;
  /* #73: @3 = (@3-@5) */
  w3 -= w5;
  /* #74: @6 = (@6*@3) */
  w6 *= w3;
  /* #75: @3 = 2 */
  w3 = 2.;
  /* #76: @6 = (@6/@3) */
  w6 /= w3;
  /* #77: @3 = 46.26 */
  w3 = 4.6259999999999998e+01;
  /* #78: @3 = (@3*@4) */
  w3 *= w4;
  /* #79: @3 = (@3*@2) */
  w3 *= w2;
  /* #80: @5 = -17.72 */
  w5 = -1.7719999999999999e+01;
  /* #81: @5 = (@5*@0) */
  w5 *= w0;
  /* #82: @5 = (@5*@4) */
  w5 *= w4;
  /* #83: @3 = (@3-@5) */
  w3 -= w5;
  /* #84: @5 = -2.25 */
  w5 = -2.2500000000000000e+00;
  /* #85: @5 = (@5*@4) */
  w5 *= w4;
  /* #86: @5 = (@5*@0) */
  w5 *= w0;
  /* #87: @3 = (@3+@5) */
  w3 += w5;
  /* #88: @6 = (@6-@3) */
  w6 -= w3;
  /* #89: @3 = -0.52 */
  w3 = -5.2000000000000002e-01;
  /* #90: @5 = sq(@4) */
  w5 = casadi_sq( w4 );
  /* #91: @8 = sq(@2) */
  w8 = casadi_sq( w2 );
  /* #92: @5 = (@5+@8) */
  w5 += w8;
  /* #93: @5 = sqrt(@5) */
  w5 = sqrt( w5 );
  /* #94: @3 = (@3*@5) */
  w3 *= w5;
  /* #95: @3 = (@3*@0) */
  w3 *= w0;
  /* #96: @3 = (-@3) */
  w3 = (- w3 );
  /* #97: @5 = -8.8 */
  w5 = -8.8000000000000007e+00;
  /* #98: @8 = fabs(@2) */
  w8 = fabs( w2 );
  /* #99: @5 = (@5*@8) */
  w5 *= w8;
  /* #100: @5 = (@5*@0) */
  w5 *= w0;
  /* #101: @3 = (@3-@5) */
  w3 -= w5;
  /* #102: @5 = -3.49 */
  w5 = -3.4900000000000002e+00;
  /* #103: @8 = fabs(@0) */
  w8 = fabs( w0 );
  /* #104: @5 = (@5*@8) */
  w5 *= w8;
  /* #105: @5 = (@5*@0) */
  w5 *= w0;
  /* #106: @3 = (@3-@5) */
  w3 -= w5;
  /* #107: @6 = (@6-@3) */
  w6 -= w3;
  /* #108: @3 = 6.89 */
  w3 = 6.8899999999999997e+00;
  /* #109: @6 = (@6/@3) */
  w6 /= w3;
  /* #110: output[0][5] = @6 */
  if (res[0]) res[0][5] = w6;
  /* #111: @6 = sin(@1) */
  w6 = sin( w1 );
  /* #112: @6 = (@4*@6) */
  w6  = (w4*w6);
  /* #113: @3 = cos(@1) */
  w3 = cos( w1 );
  /* #114: @3 = (@2*@3) */
  w3  = (w2*w3);
  /* #115: @6 = (@6+@3) */
  w6 += w3;
  /* #116: @3 = input[0][9] */
  w3 = arg[0] ? arg[0][9] : 0;
  /* #117: @5 = cos(@3) */
  w5 = cos( w3 );
  /* #118: @6 = (@6*@5) */
  w6 *= w5;
  /* #119: @5 = cos(@1) */
  w5 = cos( w1 );
  /* #120: @5 = (@4*@5) */
  w5  = (w4*w5);
  /* #121: @0 = sin(@1) */
  w0 = sin( w1 );
  /* #122: @0 = (@2*@0) */
  w0  = (w2*w0);
  /* #123: @5 = (@5-@0) */
  w5 -= w0;
  /* #124: @3 = sin(@3) */
  w3 = sin( w3 );
  /* #125: @5 = (@5*@3) */
  w5 *= w3;
  /* #126: @6 = (@6-@5) */
  w6 -= w5;
  /* #127: output[0][6] = @6 */
  if (res[0]) res[0][6] = w6;
  /* #128: @6 = 0 */
  w6 = 0.;
  /* #129: output[0][7] = @6 */
  if (res[0]) res[0][7] = w6;
  /* #130: @6 = 0 */
  w6 = 0.;
  /* #131: output[0][8] = @6 */
  if (res[0]) res[0][8] = w6;
  /* #132: @6 = 0 */
  w6 = 0.;
  /* #133: output[0][9] = @6 */
  if (res[0]) res[0][9] = w6;
  /* #134: @6 = cos(@1) */
  w6 = cos( w1 );
  /* #135: @6 = (@4*@6) */
  w6  = (w4*w6);
  /* #136: @5 = sin(@1) */
  w5 = sin( w1 );
  /* #137: @5 = (@2*@5) */
  w5  = (w2*w5);
  /* #138: @6 = (@6-@5) */
  w6 -= w5;
  /* #139: output[0][10] = @6 */
  if (res[0]) res[0][10] = w6;
  /* #140: @6 = sin(@1) */
  w6 = sin( w1 );
  /* #141: @4 = (@4*@6) */
  w4 *= w6;
  /* #142: @1 = cos(@1) */
  w1 = cos( w1 );
  /* #143: @2 = (@2*@1) */
  w2 *= w1;
  /* #144: @4 = (@4+@2) */
  w4 += w2;
  /* #145: output[0][11] = @4 */
  if (res[0]) res[0][11] = w4;
  /* #146: @4 = input[1][0] */
  w4 = arg[1] ? arg[1][0] : 0;
  /* #147: output[0][12] = @4 */
  if (res[0]) res[0][12] = w4;
  /* #148: @4 = input[1][1] */
  w4 = arg[1] ? arg[1][1] : 0;
  /* #149: output[0][13] = @4 */
  if (res[0]) res[0][13] = w4;
  return 0;
}

CASADI_SYMBOL_EXPORT int usv_model_pf_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int usv_model_pf_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int usv_model_pf_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void usv_model_pf_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int usv_model_pf_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void usv_model_pf_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void usv_model_pf_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void usv_model_pf_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int usv_model_pf_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int usv_model_pf_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real usv_model_pf_expl_ode_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* usv_model_pf_expl_ode_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* usv_model_pf_expl_ode_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* usv_model_pf_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* usv_model_pf_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int usv_model_pf_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 11;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
