/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) usv_model_pf_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sign CASADI_PREFIX(sign)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_sign(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}

static const casadi_int casadi_s0[18] = {14, 1, 0, 14, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[13] = {16, 1, 0, 9, 0, 3, 4, 5, 9, 12, 13, 14, 15};

/* usv_model_pf_expl_vde_adj:(i0[14],i1[14],i2[2],i3[])->(o0[16x1,9nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, *w3=w+3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24, w25, w26, w27, w28, w29, w30, w31, w32, w33, w34, w35;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = cos(@0) */
  w1 = cos( w0 );
  /* #2: @2 = input[0][3] */
  w2 = arg[0] ? arg[0][3] : 0;
  /* #3: @3 = input[1][0] */
  casadi_copy(arg[1], 14, w3);
  /* #4: {@4, @5, @6, @7, @8, @9, @10, NULL, NULL, NULL, @11, @12, @13, @14} = vertsplit(@3) */
  w4 = w3[0];
  w5 = w3[1];
  w6 = w3[2];
  w7 = w3[3];
  w8 = w3[4];
  w9 = w3[5];
  w10 = w3[6];
  w11 = w3[10];
  w12 = w3[11];
  w13 = w3[12];
  w14 = w3[13];
  /* #5: @15 = (@2*@12) */
  w15  = (w2*w12);
  /* #6: @1 = (@1*@15) */
  w1 *= w15;
  /* #7: @15 = sin(@0) */
  w15 = sin( w0 );
  /* #8: @16 = input[0][4] */
  w16 = arg[0] ? arg[0][4] : 0;
  /* #9: @17 = (@16*@12) */
  w17  = (w16*w12);
  /* #10: @15 = (@15*@17) */
  w15 *= w17;
  /* #11: @1 = (@1-@15) */
  w1 -= w15;
  /* #12: @15 = cos(@0) */
  w15 = cos( w0 );
  /* #13: @17 = (@16*@11) */
  w17  = (w16*w11);
  /* #14: @15 = (@15*@17) */
  w15 *= w17;
  /* #15: @1 = (@1-@15) */
  w1 -= w15;
  /* #16: @15 = sin(@0) */
  w15 = sin( w0 );
  /* #17: @17 = (@2*@11) */
  w17  = (w2*w11);
  /* #18: @15 = (@15*@17) */
  w15 *= w17;
  /* #19: @1 = (@1-@15) */
  w1 -= w15;
  /* #20: @15 = cos(@0) */
  w15 = cos( w0 );
  /* #21: @17 = input[0][9] */
  w17 = arg[0] ? arg[0][9] : 0;
  /* #22: @18 = sin(@17) */
  w18 = sin( w17 );
  /* #23: @18 = (@18*@10) */
  w18 *= w10;
  /* #24: @19 = (@16*@18) */
  w19  = (w16*w18);
  /* #25: @15 = (@15*@19) */
  w15 *= w19;
  /* #26: @1 = (@1+@15) */
  w1 += w15;
  /* #27: @15 = sin(@0) */
  w15 = sin( w0 );
  /* #28: @19 = (@2*@18) */
  w19  = (w2*w18);
  /* #29: @15 = (@15*@19) */
  w15 *= w19;
  /* #30: @1 = (@1+@15) */
  w1 += w15;
  /* #31: @15 = sin(@0) */
  w15 = sin( w0 );
  /* #32: @19 = cos(@17) */
  w19 = cos( w17 );
  /* #33: @19 = (@19*@10) */
  w19 *= w10;
  /* #34: @20 = (@16*@19) */
  w20  = (w16*w19);
  /* #35: @15 = (@15*@20) */
  w15 *= w20;
  /* #36: @1 = (@1-@15) */
  w1 -= w15;
  /* #37: @15 = cos(@0) */
  w15 = cos( w0 );
  /* #38: @20 = (@2*@19) */
  w20  = (w2*w19);
  /* #39: @15 = (@15*@20) */
  w15 *= w20;
  /* #40: @1 = (@1+@15) */
  w1 += w15;
  /* #41: @15 = 0.001 */
  w15 = 1.0000000000000000e-03;
  /* #42: @15 = (@15+@2) */
  w15 += w2;
  /* #43: @20 = atan2(@16,@15) */
  w20  = atan2(w16,w15);
  /* #44: @20 = (@0+@20) */
  w20  = (w0+w20);
  /* #45: @21 = sin(@20) */
  w21 = sin( w20 );
  /* #46: @22 = input[0][5] */
  w22 = arg[0] ? arg[0][5] : 0;
  /* #47: @23 = (@22*@5) */
  w23  = (w22*w5);
  /* #48: @21 = (@21*@23) */
  w21 *= w23;
  /* #49: @21 = (-@21) */
  w21 = (- w21 );
  /* #50: @23 = cos(@20) */
  w23 = cos( w20 );
  /* #51: @24 = (@22*@6) */
  w24  = (w22*w6);
  /* #52: @23 = (@23*@24) */
  w23 *= w24;
  /* #53: @21 = (@21-@23) */
  w21 -= w23;
  /* #54: @1 = (@1+@21) */
  w1 += w21;
  /* #55: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  /* #56: @1 = sin(@0) */
  w1 = sin( w0 );
  /* #57: @1 = (@1*@12) */
  w1 *= w12;
  /* #58: @23 = cos(@0) */
  w23 = cos( w0 );
  /* #59: @23 = (@23*@11) */
  w23 *= w11;
  /* #60: @1 = (@1+@23) */
  w1 += w23;
  /* #61: @23 = cos(@0) */
  w23 = cos( w0 );
  /* #62: @24 = (@23*@18) */
  w24  = (w23*w18);
  /* #63: @1 = (@1-@24) */
  w1 -= w24;
  /* #64: @24 = sin(@0) */
  w24 = sin( w0 );
  /* #65: @25 = (@24*@19) */
  w25  = (w24*w19);
  /* #66: @1 = (@1+@25) */
  w1 += w25;
  /* #67: @25 = (2.*@2) */
  w25 = (2.* w2 );
  /* #68: @26 = -0.52 */
  w26 = -5.2000000000000002e-01;
  /* #69: @27 = 0.145138 */
  w27 = 1.4513788098693758e-01;
  /* #70: @27 = (@27*@9) */
  w27 *= w9;
  /* #71: @9 = (@22*@27) */
  w9  = (w22*w27);
  /* #72: @9 = (@26*@9) */
  w9  = (w26*w9);
  /* #73: @28 = sq(@2) */
  w28 = casadi_sq( w2 );
  /* #74: @29 = sq(@16) */
  w29 = casadi_sq( w16 );
  /* #75: @28 = (@28+@29) */
  w28 += w29;
  /* #76: @28 = sqrt(@28) */
  w28 = sqrt( w28 );
  /* #77: @29 = (2.*@28) */
  w29 = (2.* w28 );
  /* #78: @9 = (@9/@29) */
  w9 /= w29;
  /* #79: @25 = (@25*@9) */
  w25 *= w9;
  /* #80: @1 = (@1+@25) */
  w1 += w25;
  /* #81: @25 = -2.25 */
  w25 = -2.2500000000000000e+00;
  /* #82: @29 = (@22*@27) */
  w29  = (w22*w27);
  /* #83: @29 = (@25*@29) */
  w29  = (w25*w29);
  /* #84: @1 = (@1-@29) */
  w1 -= w29;
  /* #85: @29 = -17.72 */
  w29 = -1.7719999999999999e+01;
  /* #86: @30 = (@29*@22) */
  w30  = (w29*w22);
  /* #87: @30 = (@30*@27) */
  w30 *= w27;
  /* #88: @1 = (@1+@30) */
  w1 += w30;
  /* #89: @30 = 46.26 */
  w30 = 4.6259999999999998e+01;
  /* #90: @31 = (@16*@27) */
  w31  = (w16*w27);
  /* #91: @31 = (@30*@31) */
  w31  = (w30*w31);
  /* #92: @1 = (@1-@31) */
  w1 -= w31;
  /* #93: @31 = -32.25 */
  w31 = -3.2250000000000000e+01;
  /* #94: @32 = 0.0188218 */
  w32 = 1.8821757952192736e-02;
  /* #95: @32 = (@32*@8) */
  w32 *= w8;
  /* #96: @8 = (@22*@32) */
  w8  = (w22*w32);
  /* #97: @8 = (@31*@8) */
  w8  = (w31*w8);
  /* #98: @1 = (@1+@8) */
  w1 += w8;
  /* #99: @8 = 1.25 */
  w8 = 1.2500000000000000e+00;
  /* #100: @8 = (@8<@2) */
  w8  = (w8<w2);
  /* #101: @33 = -70.92 */
  w33 = -7.0920000000000002e+01;
  /* #102: @8 = (@8?@33:0) */
  w8  = (w8?w33:0);
  /* #103: @33 = fabs(@2) */
  w33 = fabs( w2 );
  /* #104: @33 = (@8*@33) */
  w33  = (w8*w33);
  /* #105: @34 = 0.0310078 */
  w34 = 3.1007751937984496e-02;
  /* #106: @34 = (@34*@7) */
  w34 *= w7;
  /* #107: @33 = (@33*@34) */
  w33 *= w34;
  /* #108: @1 = (@1+@33) */
  w1 += w33;
  /* #109: @33 = sign(@2) */
  w33 = casadi_sign( w2 );
  /* #110: @7 = (@2*@34) */
  w7  = (w2*w34);
  /* #111: @8 = (@8*@7) */
  w8 *= w7;
  /* #112: @33 = (@33*@8) */
  w33 *= w8;
  /* #113: @1 = (@1+@33) */
  w1 += w33;
  /* #114: @33 = 1.25 */
  w33 = 1.2500000000000000e+00;
  /* #115: @33 = (@33<@2) */
  w33  = (w33<w2);
  /* #116: @8 = 64.55 */
  w8 = 6.4549999999999997e+01;
  /* #117: @8 = (@33?@8:0) */
  w8  = (w33?w8:0);
  /* #118: @33 = (!@33) */
  w33 = (! w33 );
  /* #119: @7 = -25 */
  w7 = -25.;
  /* #120: @33 = (@33?@7:0) */
  w33  = (w33?w7:0);
  /* #121: @8 = (@8+@33) */
  w8 += w33;
  /* #122: @8 = (@8*@34) */
  w8 *= w34;
  /* #123: @1 = (@1+@8) */
  w1 += w8;
  /* #124: @8 = sq(@16) */
  w8 = casadi_sq( w16 );
  /* #125: @33 = sq(@15) */
  w33 = casadi_sq( w15 );
  /* #126: @8 = (@8+@33) */
  w8 += w33;
  /* #127: @33 = (@16/@8) */
  w33  = (w16/w8);
  /* #128: @33 = (@33*@21) */
  w33 *= w21;
  /* #129: @1 = (@1-@33) */
  w1 -= w33;
  /* #130: output[0][1] = @1 */
  if (res[0]) res[0][1] = w1;
  /* #131: @1 = cos(@0) */
  w1 = cos( w0 );
  /* #132: @1 = (@1*@12) */
  w1 *= w12;
  /* #133: @12 = sin(@0) */
  w12 = sin( w0 );
  /* #134: @12 = (@12*@11) */
  w12 *= w11;
  /* #135: @1 = (@1-@12) */
  w1 -= w12;
  /* #136: @12 = sin(@0) */
  w12 = sin( w0 );
  /* #137: @18 = (@12*@18) */
  w18  = (w12*w18);
  /* #138: @1 = (@1+@18) */
  w1 += w18;
  /* #139: @0 = cos(@0) */
  w0 = cos( w0 );
  /* #140: @19 = (@0*@19) */
  w19  = (w0*w19);
  /* #141: @1 = (@1+@19) */
  w1 += w19;
  /* #142: @19 = sign(@16) */
  w19 = casadi_sign( w16 );
  /* #143: @18 = -8.8 */
  w18 = -8.8000000000000007e+00;
  /* #144: @11 = (@22*@27) */
  w11  = (w22*w27);
  /* #145: @11 = (@18*@11) */
  w11  = (w18*w11);
  /* #146: @19 = (@19*@11) */
  w19 *= w11;
  /* #147: @1 = (@1+@19) */
  w1 += w19;
  /* #148: @19 = (2.*@16) */
  w19 = (2.* w16 );
  /* #149: @19 = (@19*@9) */
  w19 *= w9;
  /* #150: @1 = (@1+@19) */
  w1 += w19;
  /* #151: @30 = (@30*@2) */
  w30 *= w2;
  /* #152: @30 = (@30*@27) */
  w30 *= w27;
  /* #153: @1 = (@1-@30) */
  w1 -= w30;
  /* #154: @30 = 0.9945 */
  w30 = 9.9450000000000016e-01;
  /* #155: @19 = 0.5 */
  w19 = 5.0000000000000000e-01;
  /* #156: @9 = -40000 */
  w9 = -40000.;
  /* #157: @11 = fabs(@16) */
  w11 = fabs( w16 );
  /* #158: @11 = (@9*@11) */
  w11  = (w9*w11);
  /* #159: @11 = (@19*@11) */
  w11  = (w19*w11);
  /* #160: @11 = (@30*@11) */
  w11  = (w30*w11);
  /* #161: @11 = (-@11) */
  w11 = (- w11 );
  /* #162: @33 = -99.99 */
  w33 = -9.9989999999999995e+01;
  /* #163: @7 = fabs(@16) */
  w7 = fabs( w16 );
  /* #164: @7 = (@33*@7) */
  w7  = (w33*w7);
  /* #165: @11 = (@11-@7) */
  w11 -= w7;
  /* #166: @7 = -5.49 */
  w7 = -5.4900000000000002e+00;
  /* #167: @35 = fabs(@22) */
  w35 = fabs( w22 );
  /* #168: @35 = (@7*@35) */
  w35  = (w7*w35);
  /* #169: @11 = (@11-@35) */
  w11 -= w35;
  /* #170: @11 = (@11*@32) */
  w11 *= w32;
  /* #171: @1 = (@1-@11) */
  w1 -= w11;
  /* #172: @11 = sign(@16) */
  w11 = casadi_sign( w16 );
  /* #173: @35 = (@16*@32) */
  w35  = (w16*w32);
  /* #174: @33 = (@33*@35) */
  w33 *= w35;
  /* #175: @11 = (@11*@33) */
  w11 *= w33;
  /* #176: @1 = (@1+@11) */
  w1 += w11;
  /* #177: @11 = sign(@16) */
  w11 = casadi_sign( w16 );
  /* #178: @30 = (@30*@35) */
  w30 *= w35;
  /* #179: @19 = (@19*@30) */
  w19 *= w30;
  /* #180: @9 = (@9*@19) */
  w9 *= w19;
  /* #181: @11 = (@11*@9) */
  w11 *= w9;
  /* #182: @1 = (@1+@11) */
  w1 += w11;
  /* #183: @11 = -76.26 */
  w11 = -7.6259999999999991e+01;
  /* #184: @11 = (@11*@34) */
  w11 *= w34;
  /* #185: @1 = (@1-@11) */
  w1 -= w11;
  /* #186: @15 = (@15/@8) */
  w15 /= w8;
  /* #187: @15 = (@15*@21) */
  w15 *= w21;
  /* #188: @1 = (@1+@15) */
  w1 += w15;
  /* #189: output[0][2] = @1 */
  if (res[0]) res[0][2] = w1;
  /* #190: @1 = -3.49 */
  w1 = -3.4900000000000002e+00;
  /* #191: @15 = fabs(@22) */
  w15 = fabs( w22 );
  /* #192: @15 = (@1*@15) */
  w15  = (w1*w15);
  /* #193: @15 = (@15*@27) */
  w15 *= w27;
  /* #194: @21 = sign(@22) */
  w21 = casadi_sign( w22 );
  /* #195: @8 = (@22*@27) */
  w8  = (w22*w27);
  /* #196: @1 = (@1*@8) */
  w1 *= w8;
  /* #197: @21 = (@21*@1) */
  w21 *= w1;
  /* #198: @15 = (@15+@21) */
  w15 += w21;
  /* #199: @21 = fabs(@16) */
  w21 = fabs( w16 );
  /* #200: @18 = (@18*@21) */
  w18 *= w21;
  /* #201: @18 = (@18*@27) */
  w18 *= w27;
  /* #202: @15 = (@15+@18) */
  w15 += w18;
  /* #203: @26 = (@26*@28) */
  w26 *= w28;
  /* #204: @26 = (@26*@27) */
  w26 *= w27;
  /* #205: @15 = (@15+@26) */
  w15 += w26;
  /* #206: @25 = (@25*@2) */
  w25 *= w2;
  /* #207: @25 = (@25*@27) */
  w25 *= w27;
  /* #208: @15 = (@15-@25) */
  w15 -= w25;
  /* #209: @25 = (@2*@27) */
  w25  = (w2*w27);
  /* #210: @29 = (@29*@25) */
  w29 *= w25;
  /* #211: @15 = (@15+@29) */
  w15 += w29;
  /* #212: @29 = sign(@22) */
  w29 = casadi_sign( w22 );
  /* #213: @7 = (@7*@35) */
  w7 *= w35;
  /* #214: @29 = (@29*@7) */
  w29 *= w7;
  /* #215: @15 = (@15+@29) */
  w15 += w29;
  /* #216: @31 = (@31*@2) */
  w31 *= w2;
  /* #217: @31 = (@31*@32) */
  w31 *= w32;
  /* #218: @15 = (@15+@31) */
  w15 += w31;
  /* #219: @31 = -17.72 */
  w31 = -1.7719999999999999e+01;
  /* #220: @32 = (@31*@22) */
  w32  = (w31*w22);
  /* #221: @32 = (@32*@34) */
  w32 *= w34;
  /* #222: @15 = (@15-@32) */
  w15 -= w32;
  /* #223: @22 = (@22*@34) */
  w22 *= w34;
  /* #224: @31 = (@31*@22) */
  w31 *= w22;
  /* #225: @15 = (@15-@31) */
  w15 -= w31;
  /* #226: @31 = sin(@20) */
  w31 = sin( w20 );
  /* #227: @31 = (@31*@6) */
  w31 *= w6;
  /* #228: @15 = (@15-@31) */
  w15 -= w31;
  /* #229: @20 = cos(@20) */
  w20 = cos( w20 );
  /* #230: @20 = (@20*@5) */
  w20 *= w5;
  /* #231: @15 = (@15+@20) */
  w15 += w20;
  /* #232: @15 = (@15+@4) */
  w15 += w4;
  /* #233: output[0][3] = @15 */
  if (res[0]) res[0][3] = w15;
  /* #234: @15 = sin(@17) */
  w15 = sin( w17 );
  /* #235: @24 = (@2*@24) */
  w24  = (w2*w24);
  /* #236: @0 = (@16*@0) */
  w0  = (w16*w0);
  /* #237: @24 = (@24+@0) */
  w24 += w0;
  /* #238: @24 = (@24*@10) */
  w24 *= w10;
  /* #239: @15 = (@15*@24) */
  w15 *= w24;
  /* #240: @15 = (-@15) */
  w15 = (- w15 );
  /* #241: @17 = cos(@17) */
  w17 = cos( w17 );
  /* #242: @2 = (@2*@23) */
  w2 *= w23;
  /* #243: @16 = (@16*@12) */
  w16 *= w12;
  /* #244: @2 = (@2-@16) */
  w2 -= w16;
  /* #245: @2 = (@2*@10) */
  w2 *= w10;
  /* #246: @17 = (@17*@2) */
  w17 *= w2;
  /* #247: @15 = (@15-@17) */
  w15 -= w17;
  /* #248: output[0][4] = @15 */
  if (res[0]) res[0][4] = w15;
  /* #249: @15 = 0.41 */
  w15 = 4.0999999999999998e-01;
  /* #250: @17 = 0.5 */
  w17 = 5.0000000000000000e-01;
  /* #251: @17 = (@17*@27) */
  w17 *= w27;
  /* #252: @15 = (@15*@17) */
  w15 *= w17;
  /* #253: @17 = (@15+@34) */
  w17  = (w15+w34);
  /* #254: output[0][5] = @17 */
  if (res[0]) res[0][5] = w17;
  /* #255: @34 = (@34-@15) */
  w34 -= w15;
  /* #256: output[0][6] = @34 */
  if (res[0]) res[0][6] = w34;
  /* #257: output[0][7] = @13 */
  if (res[0]) res[0][7] = w13;
  /* #258: output[0][8] = @14 */
  if (res[0]) res[0][8] = w14;
  return 0;
}

CASADI_SYMBOL_EXPORT int usv_model_pf_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int usv_model_pf_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int usv_model_pf_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void usv_model_pf_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int usv_model_pf_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void usv_model_pf_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void usv_model_pf_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void usv_model_pf_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int usv_model_pf_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int usv_model_pf_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real usv_model_pf_expl_vde_adj_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* usv_model_pf_expl_vde_adj_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* usv_model_pf_expl_vde_adj_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* usv_model_pf_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* usv_model_pf_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int usv_model_pf_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 15;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 49;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
