/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) usv_model_guidance_ca1_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s1[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s2[20] = {16, 1, 0, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};
static const casadi_int casadi_s3[10] = {9, 1, 0, 6, 0, 1, 3, 4, 7, 8};

/* usv_model_guidance_ca1_expl_vde_adj:(i0[8],i1[8],i2,i3[16])->(o0[9x1,6nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, *w2=w+2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17;
  /* #0: @0 = input[0][7] */
  w0 = arg[0] ? arg[0][7] : 0;
  /* #1: @1 = sin(@0) */
  w1 = sin( w0 );
  /* #2: @2 = input[1][0] */
  casadi_copy(arg[1], 8, w2);
  /* #3: {NULL, NULL, @3, @4, @5, @6, @7, @8} = vertsplit(@2) */
  w3 = w2[2];
  w4 = w2[3];
  w5 = w2[4];
  w6 = w2[5];
  w7 = w2[6];
  w8 = w2[7];
  /* #4: @1 = (@1*@7) */
  w1 *= w7;
  /* #5: @9 = cos(@0) */
  w9 = cos( w0 );
  /* #6: @9 = (@9*@6) */
  w9 *= w6;
  /* #7: @1 = (@1+@9) */
  w1 += w9;
  /* #8: @9 = input[0][3] */
  w9 = arg[0] ? arg[0][3] : 0;
  /* #9: @10 = input[0][1] */
  w10 = arg[0] ? arg[0][1] : 0;
  /* #10: @11 = 0.001 */
  w11 = 1.0000000000000000e-03;
  /* #11: @12 = input[0][0] */
  w12 = arg[0] ? arg[0][0] : 0;
  /* #12: @11 = (@11+@12) */
  w11 += w12;
  /* #13: @13 = atan2(@10,@11) */
  w13  = atan2(w10,w11);
  /* #14: @9 = (@9-@13) */
  w9 -= w13;
  /* #15: @13 = sin(@9) */
  w13 = sin( w9 );
  /* #16: @13 = (@13*@3) */
  w13 *= w3;
  /* #17: @1 = (@1+@13) */
  w1 += w13;
  /* #18: @13 = sq(@10) */
  w13 = casadi_sq( w10 );
  /* #19: @14 = sq(@11) */
  w14 = casadi_sq( w11 );
  /* #20: @13 = (@13+@14) */
  w13 += w14;
  /* #21: @14 = (@10/@13) */
  w14  = (w10/w13);
  /* #22: @15 = (-@4) */
  w15 = (- w4 );
  /* #23: @15 = (@15-@8) */
  w15 -= w8;
  /* #24: @16 = sin(@9) */
  w16 = sin( w9 );
  /* #25: @17 = (@10*@3) */
  w17  = (w10*w3);
  /* #26: @16 = (@16*@17) */
  w16 *= w17;
  /* #27: @15 = (@15-@16) */
  w15 -= w16;
  /* #28: @16 = cos(@9) */
  w16 = cos( w9 );
  /* #29: @17 = (@12*@3) */
  w17  = (w12*w3);
  /* #30: @16 = (@16*@17) */
  w16 *= w17;
  /* #31: @15 = (@15+@16) */
  w15 += w16;
  /* #32: @14 = (@14*@15) */
  w14 *= w15;
  /* #33: @1 = (@1+@14) */
  w1 += w14;
  /* #34: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  /* #35: @1 = cos(@0) */
  w1 = cos( w0 );
  /* #36: @1 = (@1*@7) */
  w1 *= w7;
  /* #37: @14 = sin(@0) */
  w14 = sin( w0 );
  /* #38: @14 = (@14*@6) */
  w14 *= w6;
  /* #39: @1 = (@1-@14) */
  w1 -= w14;
  /* #40: @9 = cos(@9) */
  w9 = cos( w9 );
  /* #41: @9 = (@9*@3) */
  w9 *= w3;
  /* #42: @1 = (@1+@9) */
  w1 += w9;
  /* #43: @11 = (@11/@13) */
  w11 /= w13;
  /* #44: @11 = (@11*@15) */
  w11 *= w15;
  /* #45: @1 = (@1-@11) */
  w1 -= w11;
  /* #46: output[0][1] = @1 */
  if (res[0]) res[0][1] = w1;
  /* #47: output[0][2] = @15 */
  if (res[0]) res[0][2] = w15;
  /* #48: @8 = (@8+@4) */
  w8 += w4;
  /* #49: output[0][3] = @8 */
  if (res[0]) res[0][3] = w8;
  /* #50: @8 = cos(@0) */
  w8 = cos( w0 );
  /* #51: @4 = (@12*@7) */
  w4  = (w12*w7);
  /* #52: @8 = (@8*@4) */
  w8 *= w4;
  /* #53: @4 = sin(@0) */
  w4 = sin( w0 );
  /* #54: @7 = (@10*@7) */
  w7  = (w10*w7);
  /* #55: @4 = (@4*@7) */
  w4 *= w7;
  /* #56: @8 = (@8-@4) */
  w8 -= w4;
  /* #57: @4 = cos(@0) */
  w4 = cos( w0 );
  /* #58: @10 = (@10*@6) */
  w10 *= w6;
  /* #59: @4 = (@4*@10) */
  w4 *= w10;
  /* #60: @8 = (@8-@4) */
  w8 -= w4;
  /* #61: @0 = sin(@0) */
  w0 = sin( w0 );
  /* #62: @12 = (@12*@6) */
  w12 *= w6;
  /* #63: @0 = (@0*@12) */
  w0 *= w12;
  /* #64: @8 = (@8-@0) */
  w8 -= w0;
  /* #65: output[0][4] = @8 */
  if (res[0]) res[0][4] = w8;
  /* #66: output[0][5] = @5 */
  if (res[0]) res[0][5] = w5;
  return 0;
}

CASADI_SYMBOL_EXPORT int usv_model_guidance_ca1_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int usv_model_guidance_ca1_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int usv_model_guidance_ca1_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void usv_model_guidance_ca1_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int usv_model_guidance_ca1_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void usv_model_guidance_ca1_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void usv_model_guidance_ca1_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void usv_model_guidance_ca1_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int usv_model_guidance_ca1_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int usv_model_guidance_ca1_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real usv_model_guidance_ca1_expl_vde_adj_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* usv_model_guidance_ca1_expl_vde_adj_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* usv_model_guidance_ca1_expl_vde_adj_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* usv_model_guidance_ca1_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* usv_model_guidance_ca1_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int usv_model_guidance_ca1_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 9;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 25;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
