/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) usv_model_guidance_ca1_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s1[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s2[20] = {16, 1, 0, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};

/* usv_model_guidance_ca1_expl_ode_fun:(i0[8],i1,i2[16])->(o0[8]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3, w4, w5, w6;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #2: @0 = 0 */
  w0 = 0.;
  /* #3: output[0][1] = @0 */
  if (res[0]) res[0][1] = w0;
  /* #4: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #5: @1 = input[0][3] */
  w1 = arg[0] ? arg[0][3] : 0;
  /* #6: @2 = input[0][1] */
  w2 = arg[0] ? arg[0][1] : 0;
  /* #7: @3 = 0.001 */
  w3 = 1.0000000000000000e-03;
  /* #8: @3 = (@3+@0) */
  w3 += w0;
  /* #9: @3 = atan2(@2,@3) */
  w3  = atan2(w2,w3);
  /* #10: @1 = (@1-@3) */
  w1 -= w3;
  /* #11: @3 = sin(@1) */
  w3 = sin( w1 );
  /* #12: @3 = (@0*@3) */
  w3  = (w0*w3);
  /* #13: @4 = cos(@1) */
  w4 = cos( w1 );
  /* #14: @4 = (@2*@4) */
  w4  = (w2*w4);
  /* #15: @3 = (@3+@4) */
  w3 += w4;
  /* #16: output[0][2] = @3 */
  if (res[0]) res[0][2] = w3;
  /* #17: @3 = input[0][4] */
  w3 = arg[0] ? arg[0][4] : 0;
  /* #18: @4 = (@3-@1) */
  w4  = (w3-w1);
  /* #19: output[0][3] = @4 */
  if (res[0]) res[0][3] = w4;
  /* #20: @4 = input[1][0] */
  w4 = arg[1] ? arg[1][0] : 0;
  /* #21: output[0][4] = @4 */
  if (res[0]) res[0][4] = w4;
  /* #22: @4 = input[0][7] */
  w4 = arg[0] ? arg[0][7] : 0;
  /* #23: @5 = cos(@4) */
  w5 = cos( w4 );
  /* #24: @5 = (@0*@5) */
  w5  = (w0*w5);
  /* #25: @6 = sin(@4) */
  w6 = sin( w4 );
  /* #26: @6 = (@2*@6) */
  w6  = (w2*w6);
  /* #27: @5 = (@5-@6) */
  w5 -= w6;
  /* #28: output[0][5] = @5 */
  if (res[0]) res[0][5] = w5;
  /* #29: @5 = sin(@4) */
  w5 = sin( w4 );
  /* #30: @0 = (@0*@5) */
  w0 *= w5;
  /* #31: @4 = cos(@4) */
  w4 = cos( w4 );
  /* #32: @2 = (@2*@4) */
  w2 *= w4;
  /* #33: @0 = (@0+@2) */
  w0 += w2;
  /* #34: output[0][6] = @0 */
  if (res[0]) res[0][6] = w0;
  /* #35: @3 = (@3-@1) */
  w3 -= w1;
  /* #36: output[0][7] = @3 */
  if (res[0]) res[0][7] = w3;
  return 0;
}

CASADI_SYMBOL_EXPORT int usv_model_guidance_ca1_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int usv_model_guidance_ca1_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int usv_model_guidance_ca1_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void usv_model_guidance_ca1_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int usv_model_guidance_ca1_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void usv_model_guidance_ca1_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void usv_model_guidance_ca1_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void usv_model_guidance_ca1_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int usv_model_guidance_ca1_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int usv_model_guidance_ca1_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real usv_model_guidance_ca1_expl_ode_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* usv_model_guidance_ca1_expl_ode_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* usv_model_guidance_ca1_expl_ode_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* usv_model_guidance_ca1_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* usv_model_guidance_ca1_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int usv_model_guidance_ca1_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 7;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
