obstacle_publisher_node:
  ros__parameters:
    mission_choice: "m2_v3"
    m1_test:
      obj_names: ["b1", "b2", "b3", "b4"]
      obj_info:
        b1:
          x: 3.5
          y: -3.0
          color: 0
          type: "marker"
        b2:
          x: 15.0
          y: -12.0
          color: 0
          type: "marker"
        b3:
          x: 5.5
          y: 0.0
          color: 1
          type: "marker"
        b4:
          x: 14.0
          y: -9.0
          color: 1
          type: "marker"
    m1:
      obj_names: ["b1", "b2", "b3", "b4"]
      obj_info:
        b1:
          x: 3.5
          y: -3.0
          color: 0
          type: "marker"
        b2:
          x: 19.0
          y: -4.1
          color: 0
          type: "marker"
        b3:
          x: 3.7
          y: 0.9
          color: 1
          type: "marker"
        b4:
          x: 17.0
          y: -1.0
          color: 1
          type: "marker"
    m2:
      obj_names: ["b1", "b2", "b3", "b4", "b5", "b6", "b7", "b8", "b9"]
      obj_info:
        b1:
          x: 3.5
          y: -3.0
          color: 0
          type: "round"
        b2:
          x: 9.0
          y: -4.1
          color: 0
          type: "round"
        b3:
          x: 13.0
          y: -2.0
          color: 0
          type: "round"
        b4:
          x: 3.7
          y: 0.9
          color: 1
          type: "round"
        b5:
          x: 8.8
          y: -1.0
          color: 1
          type: "round"
        b6:
          x: 14.0
          y: 1.23
          color: 1
          type: "round"
        b7:
          x: 6.7
          y: -2.0
          color: 3
          type: "round"
        b8:
          x: 3.2
          y: -1.5
          color: 4
          type: "round"
        b9:
          x: 13.0
          y: 0.5
          color: 4
          type: "round"
    m2_v2:
      obj_names: ["b1", "b2", "b3", "b4", "b5", "b6", "b7", "b8", "b9", "b10", "b11", "b12"]
      obj_info:
        b1:
          x: 3.5
          y: -3.0
          color: 0
          type: "round"
        b2:
          x: 9.0
          y: -4.1
          color: 0
          type: "round"
        b3:
          x: 18.0
          y: -2.0
          color: 0
          type: "round"
        b4:
          x: 19.5
          y: 2.0
          color: 0
          type: "round"
        b5:
          x: 20.0
          y: 8.1
          color: 0
          type: "round"
        b6:
          x: 18.0
          y: 15.0
          color: 0
          type: "round"
        b7:
          x: 3.7
          y: 0.9
          color: 1
          type: "round"
        b8:
          x: 8.8
          y: -1.0
          color: 1
          type: "round"
        b9:
          x: 15.0
          y: 1.2
          color: 1
          type: "round"
        b10:
          x: 17.0
          y: 3.0
          color: 1
          type: "round"
        b11:
          x: 18.5
          y: 10.1
          color: 1
          type: "round"
        b12:
          x: 19.0
          y: 18.0
          color: 1
          type: "round"
    m2_v3:
      obj_names: ["b1", "b2", "b3", "b4", "b5", "b6", "b7", "b8", "b9", "b10", 
                  "b11", "b12", "b13", "b14", "b15", "b16", "b17", "b18", "b19",
                  "b20", "b21", "b22", "b23", "b24", "b25", "b26", "b27"]
      obj_info:
        b1:
          x: 3.5
          y: 3.0
          color: 0
          type: "round"
        b2:
          x: 9.0
          y: 4.1
          color: 0
          type: "round"
        b3:
          x: 18.0
          y: 2.0
          color: 0
          type: "round"
        b4:
          x: 19.5
          y: -2.0
          color: 0
          type: "round"
        b5:
          x: 20.0
          y: -8.1
          color: 0
          type: "round"
        b6:
          x: 18.0
          y: -15.0
          color: 0
          type: "round"
        b7:
          x: 3.7
          y: -0.9
          color: 1
          type: "round"
        b8:
          x: 8.8
          y: 1.0
          color: 1
          type: "round"
        b9:
          x: 15.0
          y: -1.2
          color: 1
          type: "round"
        b10:
          x: 17.0
          y: -3.0
          color: 1
          type: "round"
        b11:
          x: 18.5
          y: -10.1
          color: 1
          type: "round"
        b12:
          x: 21.0
          y: -16.0
          color: 1
          type: "round"
        b13:
          x: 4.0
          y: 1.0
          color: 3
          type: "round"
        b14:
          x: 7.0
          y: 1.6
          color: 3
          type: "round"
        b15:
          x: 13.0
          y: 2.0
          color: 3
          type: "round"
        b16:
          x: 17.0
          y: 1.0
          color: 3
          type: "round"
        b17:
          x: 18.5
          y: -8.5
          color: 3
          type: "round"
        b18:
          x: 20.0
          y: -15.0
          color: 3
          type: "round"
        b19:
          x: 18.86663055419922
          y: -12.991207122802734
          color: 3
          type: "round"
        b20:
          x: 18.86092758178711
          y: -11.189061164855957
          color: 3
          type: "round"
        b21:
          x: 18.88315200805664
          y: -4.210023403167725
          color: 4
          type: "round"
        b22:
          x: 5.891561508178711
          y: 2.1300337314605713
          color: 4
          type: "round"
        b23:
          x: 10.892723083496094
          y: 1.1166443824768066
          color: 4
          type: "round"
        b24:
          x: 16.89728546142578
          y: -1.3939000368118286
          color: 4
          type: "round"
        b25:
          x: 18.167936325073242
          y: -7.00393533706665
          color: 4
          type: "round"
        b26:
          x: 1.839877963066101
          y: -0.509712278842926
          color: 4
          type: "round"
        b27:
          x: 16.08861541748047
          y: 2.8140804767608643
          color: 4
          type: "round"

    m3:
      obj_names: ["b1", "b2", "b3", "b4"]
      obj_info:
        b1:
          x: -1.5
          y: -3.0
          color: 0
          type: "round"
        b2:
          x: -1.5
          y: 3.0
          color: 1
          type: "round"
        b3:
          x: -13.0
          y: 10.0
          color: 2
          type: "round"
        b4:
          x: -15.0
          y: 0.0
          color: 3
          type: "round"
    m3_v2:
      obj_names: ["b1", "b2", "b3", "b4"]
      obj_info:
        b1:
          x: 8.0
          y: 9.0
          color: 0
          type: "round"
        b2:
          x: 7.0
          y: 10.5
          color: 1
          type: "round"
        b3:
          x: -13.0
          y: 10.0
          color: 2
          type: "round"
        b4:
          x: -2.0
          y: 0.0
          color: 3
          type: "round"
    m4:
      obj_names: ["picture1", "picture2", "picture3"]
      obj_info:
        picture1:
          x: 9.0
          y: 19.0
          color: 3
          type: "picture"
        picture2:
          x: 8.5
          y: 14.0
          color: 2
          type: "picture"
        picture3:
          x: 9.5
          y: 24.0
          color: 1
          type: "picture"
